### ISSUE TITLE
Request limit reached

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#150]
429 errors (too many requests) can be reached quickly when navigating on pages that perform multiple requests (current backend limitation is 100 requests per minute). Also there is no global handling of these errors as each component fail independently

**Comment by jrcastro2** [comment]
Currently:
- As a non logged user we can only perform 60 requests per minute and 1000 per hour. 
  - Actions: Use filters and access books details.
  - Estimation: As a "normal" non logged user we should do around 30 requests per minute.
  - Risk: No risk at all. Each time we access the details of a book we perform 5 requests. The only risk here is to consult 10+ books in less than a minute
	
- As a logged user the number of requests increases to 100 per minute and 5000 per hour.
  - Actions: Use filters, access books details, request a book, consult `your loans` page.
  - Estimation: As a "normal" logged user we should do around 30 requests per minute.
  - Risk: No risk at all. 5 requests per book. When accesing `your loans` page, we perform 3 requests for the `current` tab and 2 for the `history` tab, risk here is to switch a lot between these 2.
		
- As a librarian working on the backoffice, we can perform 100 requests per minute and 5000 requests per hour.
  - Actions: Perform some work as a "fast" librarian, creating diferent records, editing, consulting, creating loans, check-in ...
  - Estimation: As a librarian the amount of requests we can perform depends on what we are doing:
    - Forms: When working on forms there is no real risk, since we have the nested fields closed (this way we only perform requests to fetch data when we open it, for instance the vocabularies) and usually it should take some time to enter all the details. Number of requests per minute is low. No risk.
    - Consulting: Most of the details page perform 1, 3 or 5 request at most, except the patron details page and the document details page, these perform 13 and 9 requests respectively. Risk here is to consult 7+ patrons or 9+ documents in less than a minute.
    - Normal use: As a normal "fast" librarian if we perform some checkouts and some checkin, editing documents and consulting information, we should perform around 50 requests per minute. No risk at all.
  - Risk: Medium-low. With a normal "fast" use we should not reach the rate limit easily, but it could be that if we want to quickly consult the details of some patrons or documents we could get to see the error.
		
Overall conclusion: IMHO the rate limits are correct, we could consider increase a bit the number of requests per minute for the logged users up to 150 so it would be really hard to get the error even when consulting patrons or documents.
