### ISSUE TITLE
Size infrastructure resources

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-ils#170]
- [x] define the right number of backend containers and the max connections, based on the amount of available connection on the db
- [x] define the CPU/Memory resources assigned to each container
- [x] change sidecar krb OS (deprecation)
- [x] check lb max connection for static and non-static
- [x] check the `WSGI_PROXIES` because the IPs in the Admin panels are not correct, check https://invenio.readthedocs.io/en/latest/documentation/main-concepts/securing-your-instance.html
- [x] ~~check `set USER ${INVENIO_USER_ID}` in backend Docker images~~ `Openshift will run your app with a random user`
- [x] server time issue: it looks like that it is 1 hour behind
- [x] This [commit](https://gitlab.cern.ch/AIGROUP-cds-admin/cds-books-openshift/-/commit/c4e68bcc4e2770cd9bf8dfb95875f4a74d83ff83) fixed container [worker-beat](https://openshift.cern.ch/console/project/books-dev/browse/dc/worker-beat) but it does not have [health checks](https://openshift.cern.ch/console/project/books-dev/edit/health-checks?kind=DeploymentConfig&name=worker-beat&group=) to ensure it is running correctly. In contrast to celery worker celery beat does not support celery inspect ping. We have to come up with another way to do the health check.

**Comment by kprzerwa** [comment]
Calculate and assign correct resources (CPU/RAM) for the services.
Set up the number DB connections

- rabbit-mq: at least 1024 MB memory
- celery worker: 512 MB is not enough
