### ISSUE TITLE
migrate acquisition and inter library loans

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#172]
1. Dump the tables of acquisition orders and Interlibrary loans - in the same fashion as the previous tables, visible in our production scripts
2. Write the script to load the dumped JSON to correct record types 
3. Pay attention to manage the dependencies between loaded records.
4. test with larger amount of data

**Comment by topless** [comment]
1) In CDS, `crcILLREQUEST` is the table that holds both `ILL Borrowing Requests` (`book`, `article`) and `Acquisition Orders` (`acq-book`, `acq-standard`, `proposal-book`). They are differentiated by the mentioned values of the field `request_type`. We should probably keep this field as `legacy_request_type`.

1) Should we keep the notes? In CDS there are `library_notes` (stringified object i.e. "{}" as an empty value) and `borrower_notes`.

1) There are few fields that were not migrated/used `only_this_edition`, `overdue_letter_number`, `overdue_letter_date`.

1) For the `Acquisition Orders` should we handle differently the `statuses`: 
  - `proposal-new`
  - `proposal-on order`
  - `proposal-put aside`
  - `proposal-received`

1) `recipient` is required in ILS, and must hold the value `LIBRARY` or `PATRON`, how can we tell from the existing CDS data? If we cannot tell, which one should we use as default?

1) `copies_ordered: number` is required in `Order`, what should we use for default?

1) `vendor_pid` is required in `Order`, not stored in `crcILLREQUEST`.

1) What should we use for `payment_mode`: `INTERNAL_PURCHASE_REQUISITION` or `CREDIT_CARD`?
