### ISSUE TITLE
ILL: borrowing request remains in the "requests" as pending after being processed

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#190]
Create loan from Borrowing request, it works and the loan appears in the
Patron view but the entry remains in Your requests for new literature
as Pending. I can also cancel it, and it cancels the request for new
literature, while on Loan already.

**Comment by ntarocco** [comment]
@kprzerwa Shouldn't be in `invenio-app-ils`?

**Comment by kprzerwa** [comment]
moved to invenio-app-ils
