### ISSUE TITLE
Testing scenario: add filtering by ebooks

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#221]
Add the test scenario covering the user action:
Find all the books that have ebooks

Consult with original file:
[tests.txt](https://github.com/CERNDocumentServer/cds-ils/files/5495771/tests.txt)

remove testing scenario about searching the languages

**Comment by KonstantinaStoikou** [comment]
Testing scenario added to the user testing excel, filter works correctly.
