### ISSUE TITLE
large list of authors

### ISSUE THREAD

**Issue by FlorianCassayre** [CERNDocumentServer/cds-ils#231]
Some records to be migrated have a lot of metadata associated to them. If these are migrated as they are, the users will likely experience issues with the UI. For instance, record [1125884](https://cds.cern.ch/record/1125884/export/xm?ln=en) has 2.6k authors (!).

Since these are rare exceptions, it may be wise to set up a hard limit on the number of attributes for a record.

Test the corner case of one search page (15 results) of records each with 2k+ authors, in terms of the performance of serializers, ask the Library for the examples

**Comment by ntarocco** [comment]
Unfortunately this is a valid use case: in CDS, there will be even more than 5K. The collaboration experiments chose to list all members as authors of every paper.
The system has been designed and tested in the past to support this. But it should be tested again. To test:
* frontsite/backoffice details pages
* everywhere where the authors is injected: emails, relations?, etc..
* edit form
