### ISSUE TITLE
New literature request: prefill document information

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-ils#271]
In the literature details page in the frontsite, it will be easier for a CERN user to have a button "Purchase it for me": this should automatically create a new literature request with:
- the document automatically linked
- the patron

To clarify with the library: should it prefill the new literature request form or automatically create the request? We might have to display the form to allow the user to insert the payment method?

**Comment by PaulinaBaranowska** [comment]
It should only prefill

**Comment by sakshamarora1** [comment]
Not implementing a separate button to avoid potential confusion between physical copy purchase, borrowing, or catalog addition requests.
