### ISSUE TITLE
Importer: argument of type 'NoneType' is not iterable when using cds as provider

### ISSUE THREAD

**Issue by KonstantinaStoikou** [CERNDocumentServer/cds-ils#277]
Error occurs when using [cds-example.xml.zip](https://github.com/CERNDocumentServer/cds-ils/files/5837308/cds-example.xml.zip) (unzip before using).
Not tested with other files.
[Sentry exception](https://cds-sentry.web.cern.ch/sentry/cds-ils/issues/27055/?query=is%3Aunresolved)

Also CDS as a provider should not be visible in the UI.

**Comment by jrcastro2** [comment]
Currently we are getting this error `AttributeError: module 'dojson.contrib.marc21.model' has no attribute 'do'`. This means there is no query "matching" correclty with concrete example mentioned above. Ideally this [query](https://github.com/CERNDocumentServer/cds-ils/blob/master/cds_ils/importer/providers/cds/models/book.py#L23-L30) should "match". I am not sure what is wrong, the query or the example?
