### ISSUE TITLE
journals: 980__ 690C and 960 field

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#308]
- [x] Unexpected value: "PERI" or "31" problem
write a migration rule for journals, where
if 980__ or 690C__ == PERI:  ignore field
if 960 == 31 ignore field
else : raise exception for Unexpected value

- [x] check the low rate of importing journals, if there is no other problems

**Comment by jrcastro2** [comment]
Currently we are importing 77% of journals (1808/2343).

Most frequent errors:
- MIGRATION RULE MISSING {'555__a'}
- MIGRATION RULE MISSING {'85642x'}
- MIGRATION RULE MISSING {'866__z'}
- [UNEXPECTED INPUT VALUE]  MARC FIELD: *697C_*, input value: GroupableOrderedDict((('a', 'virTH')))
  - Different unexpected input values 
- MIGRATION RULE MISSING {'938__i'}
- [MISSING REQUIRED FIELD]  MARC FIELD: *210__*, input value: GroupableOrderedDict((('9', 'J. Phys., B')))

Less frequent errors:
- MIGRATION RULE MISSING {'866__c'}
- Impossible to convert to JSON 'eitems_ebl'
-  [MISSING REQUIRED FIELD]  MARC FIELD: *780__*,
-  ERROR in xml_to_json_dump: MIGRATION RULE MISSING {'222__b'}
-  MIGRATION RULE MISSING {'85641a'}
-  [UNEXPECTED INPUT VALUE]  MARC FIELD: *041__*, input value: GroupableOrderedDict((('a', 'jap'))),
-  [MISSING REQUIRED FIELD]  MARC FIELD: *780__*,
-  MIGRATION RULE MISSING {'246_3C'} 
-  [MISSING REQUIRED FIELD]  MARC FIELD: *022__*,
