### ISSUE TITLE
Article - Series new relation

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#325]
Librarians requested to add `article` to document type list.
The use case is supposed to provide a distinction for acquisition orders of the specific articles for users (since the acq order requires to be created on a document).

In specific case we could simply add the type without implications. 

In generic ILS case we should consider the implications of the hierarchy: journal -> periodical_issue -> article

Normally the publications should follow the above hierarchy (see example https://libguides.jcu.edu.au/harvard/journal-article)
but it is possible to have an article without an issue (happens sometimes in online publications). 
It is also possible that the library (in the meaning of ILS instance) can have only an article, without catalogued periodical issue or journal, as a standalone article, when only the `publication_info` field contains the journal information (without journal 
record in ILS)

From the point of view of circulation, we create a borrowing request on the whole periodical issue or and standalone article if the library supplies it in loanable form. Considering this, article and periodical issue should be both of document record type, so they can be loaned. 
In any case the number of standalone articles would be rather small in comparison with all the journal issues as a whole.

To handle possible relations between `article` and `periodical issue` (when the article is part of periodical issue which is existing in the db) we can:

a) create a new parent-child relation for them (potentially tricky in terms of code, and requires adding new sections on document details page)
b) create a new relation of sibling type between these documents, which would be easier to implement but conceptually wrong, when we consider the nature of relation `article-periodical issue`. It would also require adding a new tab to the relation section in the backoffice)
c) use the existing sibling relation `OTHER` with note `is article of` which again is conceptually confusing, but explained by the note. It requires minimal changes, which considering the article being corner case of the periodical issue subset of records could be the best solution.

**Comment by ntarocco** [comment]
The `ISSUE_ARTICLE` will be added with https://github.com/CERNDocumentServer/cds-ils/issues/333
