### ISSUE TITLE
document form: non blocking changes

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#331]
- [x] Imprint with Publication year should be up in the form ( more frequently used)
- [x] Identifiers should be placed up in the form
- [x] Subtitle (inside Alternative titles) is a really frequent value, it should be placed up in the form, beside the title field
- [x] Licenses -> the Creative commons licenses should be displayed on top of the list

**Comment by ntarocco** [comment]
Given that we have to change the form anyway because of https://github.com/CERNDocumentServer/cds-ils/issues/330, I suggest we just simply merge the 2 issues.

**Comment by ntarocco** [comment]
I will re-open this issue because I have forgot to take this into account when changing the form.
