### ISSUE TITLE
ui: highlight that user is on QA/Dev instance

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-ils#35]
Since the look and feel is the same for PROD/QA/Dev, user (and us) is not sure in which instance is working on.
Change the logo/highlight in some way that QA/Dev are not prod.

**Comment by FlorianCassayre** [comment]
I'm suggesting the following branding (top-left corner ribbon):

```jsx
<Popup
 content="This is a development environment"
 trigger={<Label as="a" color="red" corner="left" icon="code" />}
/>

<Popup
 content="This is a pre-production version"
 trigger={<Label as="a" color="blue" corner="left" icon="certificate" />}
/>
```

![image](https://user-images.githubusercontent.com/9027075/95075610-c3284700-0710-11eb-9a54-e383372359fa.png)

![image](https://user-images.githubusercontent.com/9027075/95075776-0e425a00-0711-11eb-88df-1285203d0a39.png)

![image](https://user-images.githubusercontent.com/9027075/95075689-eeab3180-0710-11eb-9f13-52ab74475f65.png)

(note that the pre-prod would have the CERN overlay instead)

The production version would obviously not have any ribbon.

**Comment by topless** [comment]
I would use green instead of red, in order to encourage tampering with the `development environment`.
Another easy win, might be to change the `@fsPrimaryColor` and then all the `orange` elements in our page could match the color of the label.

**Comment by ntarocco** [comment]
> I would use green instead of red, in order to encourage tampering with the `development environment`.
> Another easy win, might be to change the `@fsPrimaryColor` and then all the `orange` elements in our page could match the color of the label.

I am not sure that it is easy to change the CSS per env, since we have the same code deployed in all ENVs. Something to investigate.

**Comment by FlorianCassayre** [comment]
Todo: update `.env` in `cds-ils`.
