### ISSUE TITLE
11 valid accounts with ongoing loans not migrated because non-CERN email address

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#460]
- [ ] Migrate missing users: 
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=10479 | https://phonebook.cern.ch/search?q=785076
-- | --
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=10654 | https://phonebook.cern.ch/search?q=773580
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=10700 | https://phonebook.cern.ch/search?q=411545
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=1898 | https://phonebook.cern.ch/search?q=475074
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=4537 | https://phonebook.cern.ch/search?q=708272
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=5563 | https://phonebook.cern.ch/search?q=644725
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=612 | https://phonebook.cern.ch/search?q=431120
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=6990 | https://phonebook.cern.ch/search?q=755385
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=700 | https://phonebook.cern.ch/search?q=383174
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=7515 | https://phonebook.cern.ch/search?q=401676
https://cds.cern.ch/admin2/bibcirculation/get_borrower_details?ln=en&borrower_id=7713 | https://phonebook.cern.ch/search?q=483373

- [ ] Migrate the corresponding loans (not yet migrated)

**Comment by kprzerwa** [comment]
closing as duplicate
