### ISSUE TITLE
List of loans to be modified in the Library catalogue

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#469]
[Loans_Documents_to_be_modified.xlsx](https://github.com/CERNDocumentServer/cds-ils/files/6365907/Loans_Documents_to_be_modified.xlsx)

- [ ] In Sheet loans, you'll find the ongoing loans currently linked with Migrated unknown item. 
Column A: Loan PID
Column B: Item where to attach the loan
=> Please change the loans to the correct item

- [ ] In Sheet documents, you'll find the manually migrated documents today. 
Column A: CDS Recid
Column B: ILS pid
Column C: Creation date (when needed)
Column D: Type of record: ILSSYNC or Migrated
Column E: Indication when the initial record became a MULTIPART + VOLUMES (Not sure how you do the linking in this case)
=> Please Ensure the redirection is done correctly for the Migrated items, and linking is ok for ILSSYNC.

**Comment by kprzerwa** [comment]
done
