### ISSUE TITLE
Search breaks when we start a search with a number

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#473]
Search changes the search phrase when we start a search with a number

1. Go to https://catalogue.library.cern
2. Type "1989 JINR" in the search bar
3. The search is cut after "1989"

<img width="1149" alt="Screenshot 2021-04-23 at 11 17 26" src="https://user-images.githubusercontent.com/12181904/115849925-a8f05500-a425-11eb-96d0-a177e4de5e40.png">

Expected behaviour: The search should be complete

**Comment by ntarocco** [comment]
@agentilb This happens only from the homepage, and not from the search page. Can you please confirm it?

**Comment by agentilb** [comment]
Indeed, it doesn't happen on the search page, but it happens on the detailed page of a document.
Ex. 
On https://catalogue.library.cern/literature/xdgd0-qnm36
Type: 1989 JINR
The search will be cut after the 1989
