### ISSUE TITLE
Serials - add series_type to all serial

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#477]
add series_type to all the serial records, in order to be able to filter them out in the users search

**Comment by ntarocco** [comment]
@agentilb can you please always provide a link?

Series will always appear: what we agreed is that each document in the serial will not appear, and this is what is happening.

**Comment by agentilb** [comment]
@ntarocco 

We do not want to hide the documents attached to serials. 
What we want is
- to hide the serial records for the search results. 
- or if not possible to hide them, we should be able to filter them to remove them from the search results via the facet.

Here is the link of my query: 
https://catalogue.library.cern/search?q=Introduction&l=grid&order=asc&p=1&s=15&sort=bestmatch

**Comment by ntarocco** [comment]
This is different from what was agreed. We can discuss this in the future.

**Comment by agentilb** [comment]
As a solution, we can leave the series in the search results, but be able to facet them. It is possible if the series have the following metadata: 
- Mode of issuance: Serial 
- Series type: Serial

Could we modify the metadata for all existing series which have the mode of issuance: Serial and series type:None? 
They will then appear in the facets. 

The facet should be named: "Book series" and not "Serial".
