### ISSUE TITLE
Redirection of Journals doesn't work

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#481]
**Describe the bug**
When looking at a migrated journal in CDS, the redirection doesn't wok: 
https://cds.cern.ch/record/2717127?ln=en
=>https://catalogue.library.cern/legacy/2717127

**To Reproduce**
1. https://cds.cern.ch/record/2717127?ln=en
2. We get a "Page not found"

**Expected behavior**
We should be redirected to the correct Journal in the Library catalogue.

**Comment by FlorianCassayre** [comment]
I observed a related issue; when following the "legacy" links, the frontend briefly shows up a 404 page while the document is loading before correctly displaying the content. For instance: [https://catalogue.library.cern/legacy/2275341](https://catalogue.library.cern/legacy/2275341)
