### ISSUE TITLE
Error message when returning a book

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#484]
**Describe the bug**
An error message is displayed when returning a book, but there is the return has been registered successfully. 

**To Reproduce**
- https://catalogue.library.cern/backoffice/checkin
- Check-in the book "B00000365"

**Expected behavior**
There shouldn't be an error page. 

**Screenshots**
<img width="1196" alt="Screenshot 2021-04-26 at 10 05 51" src="https://user-images.githubusercontent.com/12181904/116049902-2959c480-a677-11eb-847e-2463a0ab4894.png">

https://cds-sentry.web.cern.ch/sentry/cds-ils/issues/27539/?environment=sandbox&referrer=alert_email

**Comment by kprzerwa** [comment]
the issue was solved
