### ISSUE TITLE
Some literature covers are missing

### ISSUE THREAD

**Issue by FlorianCassayre** [CERNDocumentServer/cds-ils#485]
**Describe the bug**

Some literatures have neither a cover nor a placeholder (just an empty space). I didn't find an existing ticket for this issue, please close it if there is one already.

**To Reproduce**

Visit the following page: [https://catalogue.library.cern/literature/4w3cg-ngc37](https://catalogue.library.cern/literature/4w3cg-ngc37)

* The literature cover is missing.

**Expected behavior**

If the literature has no meaningful cover available then it should fall back to the placeholder.

**Screenshots**

![image](https://user-images.githubusercontent.com/9027075/116082973-58cef800-a69c-11eb-9613-155791ed81d7.png)

**Additional context**

It seems the server returns an HTML document instead of an image resource ([example](https://secure.syndetics.com/index.aspx?client=cernlibrary&ISBN=9782271115713/LC.gif)), which cannot be displayed in an `<img />` tag.

**Comment by kprzerwa** [comment]
thanks for staying alert :)
all the covers have been recreated

**Comment by FlorianCassayre** [comment]
Wonderful, looks much better!
However I have still managed to find a literature with the same issue as described above : [qf67x-wb979](https://catalogue.library.cern/literature/qf67x-wb979)
