### ISSUE TITLE
Loan created with wrong start and end date

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#498]
https://catalogue.library.cern/backoffice/loans/575cg-ts426
https://catalogue.library.cern/backoffice/loans/b8ejm-esr37

**Comment by agentilb** [comment]
Other example.
https://catalogue.library.cern/backoffice/loans/wf4h0-1ew90

The loan was done just before the checkin.
The loan date is correct, but the checkin date is marked as 2021-04-28

**Comment by agentilb** [comment]
Another case happened this morning: the loan date is 28/04/2021, but the loan request was created on 06/05/2021. 

See the screenshot: 

![Screenshot_2021-05-07 CERN Library Catalogue(3)](https://user-images.githubusercontent.com/12181904/117435672-656e0e80-af2e-11eb-96bc-06153059cce1.png)

**Comment by agentilb** [comment]
Another example: the check-out and the check-in were done today: 
https://catalogue.library.cern/backoffice/loans/cs58b-yc538

<img width="1194" alt="Screenshot 2021-05-10 at 17 01 14" src="https://user-images.githubusercontent.com/12181904/117680355-5e0a6780-b1b1-11eb-8e91-8d4a8b17a661.png">
