### ISSUE TITLE
Show an error message when a Librarian wants to delete a document which has dependancies

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#501]
**Is your feature request related to a problem? Please describe.**
When we delete a document, there is no alert if there is an e-item, an acquisition order or a borrowing request linked to it. We should get an alert, as there should be an alert in case of ANY dependencies with the document: items, e-items, acquisitions, borrowing request, relation, series...)

**Describe the solution you'd like**
Show a message for any dependancy linked to a document., when we try to delete it.

**Comment by kprzerwa** [comment]
note for future discussions: series will not be added to the notification, as they are considered as a parent record for the document, therefore they are not blocking for the document deletion (also series should not be blocking the deletion because they can have other document attached)
