### ISSUE TITLE
Request new literature: when declining with reason Other -> Internal Server Error

### ISSUE THREAD

**Issue by salomerohr** [CERNDocumentServer/cds-ils#506]
Request new literature: when declining with reason Other -> Internal Server Error
![Screenshot_2021-05-07 CERN Library Catalogue](https://user-images.githubusercontent.com/80258882/117413677-89255a80-af16-11eb-99de-e73889de3530.png)
but the request has well the status Declined after that
![Screenshot_2021-05-07 CERN Library Catalogue(1)](https://user-images.githubusercontent.com/80258882/117413686-8b87b480-af16-11eb-9153-e4a1b6b49ea4.png)

**Comment by kprzerwa** [comment]
it was fixed in one of previous deployments
