### ISSUE TITLE
Improve the search behaviour

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#529]
**Is your feature request related to a problem? Please describe.**
Some users might be confused by the search behaviour, it is high visible for the standards (#516), but it creates confusion on other document types as well.  

2 aspects seem to be improved: 
- When searching 2 or more terms in the search, the implicite boolean should be AND and not OR (this is the case in Inspire)
- The order of the terms shouldn't have an impact on the search results, especially if they are part of the title and the author. 

Some examples are explained here: 
https://docs.google.com/document/d/1Xw4I4sOwHTNqKYR6JrhOfMkPwlNTuE4cmZgGKmbTzDE/edit#

**Comment by salomerohr** [comment]
Another example where it should be an AND between the words:
authors.full_name:(Albert Einstein) - literature from a specific author
