### ISSUE TITLE
Loan request- disable the checkout button

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#532]
When dealing with a loan request, we anyway scan the barcode to register the loan. The checkout button can be a source of error, because you can select the wrong line. 
It would be better to disable this button. 

<img width="798" alt="Screenshot 2021-05-31 at 17 16 07" src="https://user-images.githubusercontent.com/12181904/120213963-22087680-c234-11eb-9226-04ce4566c656.png">

**Comment by kprzerwa** [comment]
discussed in person, closing
