### ISSUE TITLE
Vocabulary changes

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#534]
- [x] Everywhere: "e-book" -> "ebook"
- [x] BackOffice menu: "Requests for new literature" -> "Document requests"
- [x] BackOffice menu: "Series/Monographs" -> "Series/Multiparts"
- [ ] BackOffice menu: "Books/Articles" -> "Books/Proceedings/Standards"
- [x] Literature request: "Review and accept your book request!" -> "Review and accept the document request!"
- [ ] Literature request: "Select Provider" -> "Select Interlibrary loan or Acquisition"
- [ ] Patron profile, history: "Your past loans"  "Return on" -> "Returned on"

**Comment by kprzerwa** [comment]
> Everywhere: "e-book" -> "ebook"

will be renamed to Oxford Dictionary version (e-book)

> BackOffice menu: "Series/Monographs" -> "Series/Multiparts"

agreed in Zoom conversation that we will keep "monographs" as standarised name in the domain

> BackOffice menu: "Requests for new literature" -> "Document requests"

"Requests for new literature" was agreed on as a result of the user testing, since the original "Document requests" was found confusing
