### ISSUE TITLE
Hide restricted records from the Frontsite

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#535]
**Is your feature request related to a problem? Please describe.**
For the time being the restricted records are visible for the Librarians from the frontside. This is ok because those records are not visible to the users. However, we would like to hide them even for the Librarian. 
- So we are sure to have exactly the same view as the user when we go on the frontsite
- when there will be many restricted records it will be better to have a place where we are sure not to have  restricted records in the search results

**Describe the solution you'd like**
- Hide the restricted records from the frontside, have them only searchable from the back office

**Comment by kprzerwa** [comment]
discussed in person, closing
