### ISSUE TITLE
Fields not pushed from literature requests when creating a document and a purchase order

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#536]
**Describe the bug**
When the Librarian is dealing a literature request, she/he can create a document from the metadata included in the request, some of the metadata are not automatically pushed to the document: 
- Publisher
- Publication info pages
- Standard number
When he/she creates the purchase order, the budget code and payment methods is not automatically pushed to the Purchase order line. 

**Expected behavior**
- Those data should automatically be pushed in the correct fields: 
Page -> document.publication_info.
Standard number -> document.identifier (scheme:standard number)
Publisher -> document.publisher
Payment method -> Purchase order /  Order line / Payment mode
Payment information -> Purchase order /  Order line / Budget code

**Comment by zzacharo** [comment]
# Steps to reproduce

1. Login with CERN account.
2. Navigate to Help-> Request new document (loan or purchase)
3. Fill in all the information. Note to select `Purchase` in the `Request type`
4. Navigate to the backoffice and click on "Overview/Requests for new literature"
5. FInd your request and click on "Create a new document".
6. You will see that the form is missing the information mentioned above that was already saved in the request.
