### ISSUE TITLE
Migration bug: duplicates in the series 

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#541]
**Describe the bug**
It seems that during the migration, some book series have been created with duplicate. This is probably due to the fact that hat the series coming from proceedings records were done after the migration, maybe the matching with existing series was omitted? 

**To Reproduce**

It concerns series with mode of issuance Serial (Series type: NOT periodical). 

Ex. 
https://catalogue.library.cern/backoffice/series/d06wc-h4382
https://catalogue.library.cern/backoffice/series/tzwzz-ps385

https://catalogue.library.cern/backoffice/series/3wa1c-hqf92
https://catalogue.library.cern/backoffice/series/mqzje-76v24

https://catalogue.library.cern/backoffice/series/b6yyv-0e397
https://catalogue.library.cern/backoffice/series/cr2g4-acg88

**Expected outcome**
- Identify the duplicates (Based on title and ISSN if exists)
- Attach all documents to the same Series
- Delete the duplicate series 

Note: We can do the correction manually if you can provide us with the list of duplicates, except in the few cases where there are more than 20 records attached to the series.

**Comment by salomerohr** [comment]
Hi Karolina, could you please let me know once it is solved and if I need to do some manually? I am a bit stuck with the ebook importations due to this issue:
e.g.: https://catalogue.library.cern/backoffice/importer/task/209 
almost 450 with errors 'str: Multiple series found.'
Thanks a lot!

**Comment by kpsherva** [comment]
issue solved on our side, by automatic script
