### ISSUE TITLE
Problem with document form when updating a standard 

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#551]
**Describe the bug**
- When trying to edit this record: 
https://catalogue.library.cern/backoffice/documents/cvbss-zdb50/edit
(i.e. adding a value in the field edition)
The system sends an error message on the field: "extensions.standard_review_validity: Unknown field."

So it is impossible to modify the record. 

**To Reproduce**
<img width="1230" alt="Screenshot 2021-07-05 at 10 37 27" src="https://user-images.githubusercontent.com/12181904/124447158-6500c100-dd81-11eb-9cf9-b73e20846c3e.png">
<img width="1230" alt="Screenshot 2021-07-05 at 10 37 19" src="https://user-images.githubusercontent.com/12181904/124447179-69c57500-dd81-11eb-9b20-9e97f870f5c9.png">

**Comment by kprzerwa** [comment]
issue fixed
