### ISSUE TITLE
Precise search for Author names

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#573]
**Is your feature request related to a problem? Please describe.**
Use case: a user wants to look for an author with the last name "Otto", but "Otto" can also be a first name. He would like to exclude "Otto" as a first name. 
The search query to be used is: `authors.full_name.keyword: /Otto, .+/`
Which is quite complex for a standard user, and there is no documentation in the Search guide. 
See RQF1844438.  

**Describe the solution you'd like**
- Have at least this query documented in the Search guide
- We should be able to provide the users an easy way to search more precisely for authors (this is particularly useful for common names which can be first and last names). A possible solution would be to be able to browse the results by author name (using the Author index), the user would be able to select the author name he is looking for.

**Comment by kprzerwa** [comment]
implemented as a part of another ticket (the query will be documented in the search guide)
