### ISSUE TITLE
Conference country field (conference_info.country) is not visible and not editable in the Document form

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#579]
**Describe the bug**
- The conference_info.country exists in the data:
Ex. https://catalogue.library.cern/api/documents/9ac8p-zfs95
But this information is not editable when you open the document form: 
<img width="1178" alt="Screenshot 2021-08-06 at 13 13 51" src="https://user-images.githubusercontent.com/12181904/128502325-9b32dd31-f150-4ad7-bd67-7f9c398d6081.png">

**Expected behavior**
We should be able to edit and add country information in the field.

**Comment by zzacharo** [comment]
The UI should be able to handle 3-letter country names if these exist. Currently, I see that only 2 name letters are searchable in the UI and that might cause the problem described here.

<img width="573" alt="Screenshot 2021-09-13 at 11 45 16" src="https://user-images.githubusercontent.com/22594783/133062355-a33f9c27-59ac-4945-ac6e-368bd1f2fb1f.png">
