### ISSUE TITLE
CDS -> ILS Synchronisation - Library feedback

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#604]
The synchronisation works well and meets our needs. 
It is fine running the script ever day with the modifications of the latest 24h. 

Here are few modifications to be done: 
- [x] Ignore 562__ $$c
- [x] Ignore 693__ $$s
- [x] Error messages to be clarified str: [UNEXPECTED INPUT VALUE] Ex. https://sandbox-cds-ils.web.cern.ch/backoffice/importer/task/108 -> line 4
- [x] Error messages to be clarified str: None is not of type 'string' Ex. https://sandbox-cds-ils.web.cern.ch/backoffice/importer/task/108 -> line 6
- [x] Previous imports, show the latest 20 rows and not the 10 latest rows (in case we cannot check the synchro everyday, and have other imports in the meantime...)
- [x] Creation of new e-items for new records: could we use the same rules as during the migration? If not possible, select by default Not Open Access.
- [x] For the 1st synchro on production side, we need to get the modified records since the migration (21/04/2021), since all the ILSYNC records have been updated since then, we need to be able to check the logs in a file (it will be easier than checking 80 webpages...).

**Comment by kprzerwa** [comment]
the last point will be solved by the upcoming filtering feature
