### ISSUE TITLE
Bug - extend all loans should be possible even for overdue loans

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#621]
It is impossible to use this feature for loans that are already overdue, but it should be possible: it happens often that people renew after the overdue date. 

The rule should be that we are able to use this feature for loans overdue, or to expire in the next 3 days (and as it is already the case, when this is not an external loan and when the book is not requested by someone else).

**Comment by Pineirin** [comment]
Only on back office (as a librarian).

**Comment by NRodriguezcuellar** [comment]
As a librarian it is a useful feature to be able to extend overdue loans in addition to the current expiring loans. This should only be possible in the backoffice because the wanted behaviour is for patrons to return their items on time 😄 .

**Comment by agentilb** [comment]
It is possibly true for other libraries but at CERN Library, we are more flexible, and we want users to be able to extend loans even if they are overdue. Users don't always think of renewing on time. 

The only restriction for us is if one book is requested by someone else, in this case indeed, the user shouldn't be able to renew this specific book.

**Comment by ntarocco** [comment]
> It is possibly true for other libraries but at CERN Library, we are more flexible, and we want users to be able to extend loans even if they are overdue. Users don't always think of renewing on time.
> 
> The only restriction for us is if one book is requested by someone else, in this case indeed, the user shouldn't be able to renew this specific book.

Thank you, @agentilb, for the feedback, the change has been implemented as you requested.
