### ISSUE TITLE
Importer - feedback 02/11/2021

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#652]
**All sources**
- [x] Field 245, the indicators can be the following: 1st = 0 or 1 - 2nd = 0,1,2,3,4,5,6,7,8,9
See errors in https://sandbox-cds-ils.web.cern.ch/backoffice/importer/task/187
- [x] Field 100, the indicators can be the following: 1st = 0,1,3 - 2nd= empty or # 
- [x] The conversion of series should be done in the same way across the different sources: for EBL, the series title are created  without capital letters and for SPRINGER they are with capital letters. => Always keep the title as it is in the original file (but do the matching **ignoring** the case).  

**Springer import**
https://sandbox-cds-ils.web.cern.ch/backoffice/importer/task/184

- [x] BLOCKER When there is an existing  e-item (EBL or SAFARI), the importer should replace the existing item with the SPRINGER e-item, it doesn't seem to be the case anymore: ex. line 3 [978-981-15-0368-9], the existing EBL item is not deleted, and the SPRINGER item is not created. 
- [x] Lines 30 [978-3-030-00386-9]: 2 e-items seem to have been modified, but one is not working if we click on it: ex. https://sandbox-cds-ils.web.cern.ch/backoffice/eitems/mbwmz-sqb98 why is the problem here?
- [x] Line 42 [978-981-16-3568-7]: no e-item has been created, why? 
- [x] Line 6 [978-3-030-35709-2]: Error: "str: Multiple series found. " -> the importer indicates an error, however it seems the record has been created anyway, but without e-item. => the e-item should be created, and we can check the series manually.
- [x] The print ISBN (from 77680$z) seems correctly added for the updated records, but not for new records. Ex: Line 2 [978-3-030-26025-5]. 
- [x] BLOCKER The language "English" is still not added to the records, it should be added by default. 

**EBL import**
https://sandbox-cds-ils.web.cern.ch/backoffice/importer/task/181

- [x] When there is not defined role for the Author in the MARCXML (field 700 and field 100, $e), the role should be "Author" by default. (It works for SAFARI and SPRINGER).
- [x] BLOCKER There is still an issue with the matching of series, ex: https://sandbox-cds-ils.web.cern.ch/backoffice/series/dvt81-abk37 (existing series), and a new series has been created:  https://sandbox-cds-ils.web.cern.ch/backoffice/series/msdf5-krj06 : the only difference is the capital letters in one. The case SHOULD NOT be taken into account in the matching. 
- [x] Line 55 [EBC5927109]: Error: "str: Multiple series found. " -> the importer indicates an error, but it seems the record has been created anyway, but without e-item. => the e-item should be created, and we can check the series manually. 
 
**EBL delete**
https://sandbox-cds-ils.web.cern.ch/backoffice/importer/task/188

- [x] it seems the deletion doesn't work as it was working before: ID of records are not always indicated, see line 1 and 2. Why the id is not visible there? And the e-item is not deleted, nor the document. Why? This happens for many documents (110 on 627)
- [x] Line 22, it seems there were 2 e-items. It is strange there were 2 EBL e-items on the same document. We cannot check them anymore since they were deleted. Would it be possible to check what were those e-items, and if it is normal they were both deleted? 

**SAFARI delete**
https://sandbox-cds-ils.web.cern.ch/backoffice/importer/task/190

- [x] Many e-items, and documents not deleted: ex. line 5, the document exists in sandbox, but the e-item is not deleted, nor the document: https://sandbox-cds-ils.web.cern.ch/literature/kxts4-ys022 (same problem as mentioned for EBL)

**Comment by kprzerwa** [comment]
> Many e-items, and documents not deleted: ex. line 5, the document exists in sandbox, but the e-item is not deleted, nor the document: https://sandbox-cds-ils.web.cern.ch/literature/kxts4-ys022 (same problem as mentioned for EBL)

the title does not match in this case. Any other cases in safari? You mentioned many...

**Comment by kprzerwa** [comment]
@agentilb for some cases we are missing the example files you have used for testing

**Comment by kprzerwa** [comment]
> The print ISBN (from 77680$z) seems correctly added for the updated records, but not for new records. Ex: Line 2 [978-3-030-26025-5].

the subfield you have given in the mapping for the ISBN value was "a" not "z", that is why the identifiers are not added as expected. 
I will change the subfield identifier to "z" since the example file contains only this subfield, there was no "a" . If you would prefer to change it, please let me know

**Comment by agentilb** [comment]
For the deletions, I saw your comment. The title shouldn't be taken into account in this case, because we might have cleaned it between the import and the deletion, therefore, if we not match at the deletion the example in the ticket shows exactly that case. So for deletions, if the identifiers match (ISBN + provider identifier), the deletion should happen without further checks.
