### ISSUE TITLE
ebook vs. e-book in the URL descriptions of e-items

### ISSUE THREAD

**Issue by salomerohr** [CERNDocumentServer/cds-ils#659]
Some have 'ebook': https://catalogue.library.cern/backoffice/eitems?q=urls.description%3A%28ebook%29&l=list&order=asc&p=1&s=15&sort=bestmatch 
Some have 'e-book': https://catalogue.library.cern/backoffice/eitems?q=urls.description%3A%28e-book%29&l=list&order=asc&p=1&s=15&sort=bestmatch

It would be good to harmonize to 'ebook'.

**Comment by kprzerwa** [comment]
the description should be updated to "e-book",  the form used by the Oxford Dictionary

**Comment by salomerohr** [comment]
There is still both 'ebook' and 'e-book' in the catalogue. Could you please bulk update the e-items?
