### ISSUE TITLE
Undefined identifier on SAFARI Ebook

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#671]
We noticed a few records that have an "Undefined identifier":
ex. https://catalogue.library.cern/backoffice/documents/0v6hy-hta91

<img width="1253" alt="Screenshot 2021-11-15 at 10 29 32" src="https://user-images.githubusercontent.com/12181904/141756929-7df9286e-7ed1-4d54-8551-d0ec593f93dd.png">

What is the issue with this? Is it due to a problem with the migration?

**Comment by kprzerwa** [comment]
Technical solution:
remove blank values from react-jsonschema forms before submit, the value was displayed due to empty JSON object in the form

**Comment by kprzerwa** [comment]
tested, the json schema form works correctly
cannot reproduce on other records
