### ISSUE TITLE
Patron profile (user view)  - list of loans

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#672]
Some users would like to be able to see all their loans on one page. Many users have a high number of loans. 
For the time being, we display only 5 loans on a single page. 
Is it possible to display by default a higher number of loans on this page (e.g. 30)? 

<img width="716" alt="Screenshot 2021-11-17 at 07 57 34" src="https://user-images.githubusercontent.com/12181904/142149690-0500a540-8b93-42a7-bf05-7b4918cdaf56.png">
<img width="716" alt="Screenshot 2021-11-17 at 07 57 45" src="https://user-images.githubusercontent.com/12181904/142149698-33ec0783-7849-4fcb-bcb9-17e09a54e764.png">

**Comment by ntarocco** [comment]
We have discussed this feature, and we have decided that the best user experience here would be to. For each of the sections in `Current` and `History` tabs:
1. add the pagination component on the top and on the bottom
2. add a test that says something similar to `Showing 5 out of x`
3. add a `show all` button to display all of them when clicked
