### ISSUE TITLE
Home page modifications

### ISSUE THREAD

**Issue by salomerohr** [CERNDocumentServer/cds-ils#728]
There are currently the following categories on the home page:

Most recent books
Most recent ebooks
Most loaned books

Would it be possible to change for:

Most recent books and e-books 
Journals & e-journals 
~~Most recent standards~~
Most loaned books 

We regularly receive questions from patrons about where are the journals and standards and would like to highlight that they are in the catalogue (they don't notice it) and that there are not only books.

**Comment by kpsherva** [comment]
agreed to add a small section redirecting to standards provider. To be decided on how it is presented

**Comment by lydipi** [comment]
Ok for me!
