### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by salomerohr** [CERNDocumentServer/cds-ils#729]
Would it be possible to change some words to improve comprehension:

Borrowing requests:
Due date -> Returned date

Purchase orders :
Internal purchase requisition ID (DAI)
ID of inter-departmental transfer (TID)
IDT ID -> TID ID
IPR ID -> DAI ID

Search bar:
ebooks -> e-books

Left menu:
Series / Monographs -> Series / Multipart

**Comment by salomerohr** [comment]
e-book vs. ebook: 
https://catalogue.library.cern/backoffice/eitems?q=urls.description%3A%22ebook%22&l=list&order=asc&p=1&s=15&sort=bestmatch 
vs. 
https://catalogue.library.cern/backoffice/eitems?q=urls.description%3A%22e-book%22&l=list&order=asc&p=1&s=15&sort=bestmatch 
-> I thought that the chosen word was 'e-book' according to the form used by the Oxford Dictionary.

**Comment by salomerohr** [comment]
harmonize ebook / e-book in e-items.

**Comment by salomerohr** [comment]
On the form: https://sandbox-cds-ils.web.cern.ch/backoffice/acquisition/orders/create
Internal purchase requisition ID -> please add 'DAI' in parenthesis at the end
ID of inter-departmental transfer -> please add 'TID' in parenthesis at the end

I still see 'ebooks' in the Search bar in the front office:
ebooks -> e-books

I do not see this change. I still see 'Monographs':
Left menu:
Series / Monographs -> Series / Multipart

**Comment by lydipi** [comment]
In addition to Salomé's comments, could you please change "Returned Date" with "Returned date":
<img width="1163" alt="Capture d’écran 2024-03-13 à 11 41 20" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/960db55e-4c6b-4f5c-ae1a-7779fe272950">
