### ISSUE TITLE
Improve visibility of volume number and title for multipart monograph

### ISSUE THREAD

**Issue by salomerohr** [CERNDocumentServer/cds-ils#734]
For multipart monograph, the volume number and multipart title are important and should be, if possible, more visible on the detailed display to easily distinguish the volumes and the multipart they are attached to:
https://catalogue.library.cern/literature/pcdbe-ncd44 -> Handbook of particle detection and imaging (vol: 2)
https://catalogue.library.cern/literature/a3eza-72r60 -> Handbook of particle detection and imaging (vol: 1)

**Comment by kpsherva** [comment]
proposal, placing "vol:  1" in the corner indicated by red rectangle
<img width="1203" alt="Screenshot 2024-02-16 at 17 54 35" src="https://github.com/CERNDocumentServer/cds-ils/assets/38131488/78ee9716-e808-4fad-98d9-9561fd5c628c">

**Comment by salomerohr** [comment]
Yes, looks good!

**Comment by lydipi** [comment]
Perfect for the volume number!
For the multipart title, I don't see any difference? would it be possible to make it more visible?

**Comment by salomerohr** [comment]
Nice!
