### ISSUE TITLE
e-item source: make search case-insensitive

### ISSUE THREAD

**Issue by salomerohr** [CERNDocumentServer/cds-ils#739]
https://catalogue.library.cern/backoffice/eitems?q=%28source%3A%22safari%22%29&l=list&order=asc&p=1&s=15&sort=bestmatch
vs. 
https://catalogue.library.cern/backoffice/eitems?q=%28source%3A%22SAFARI%22%29&l=list&order=asc&p=1&s=15&sort=bestmatch

https://catalogue.library.cern/backoffice/eitems?q=%28source%3A%22SPRINGER%22%29&l=list&order=asc&p=1&s=15&sort=bestmatch
vs. 
https://catalogue.library.cern/backoffice/eitems?q=%28source%3A%22springer%22%29&l=list&order=asc&p=1&s=15&sort=bestmatch

**Comment by salomerohr** [comment]
Medium
Recipient
Provider
are also affected.

**Comment by salomerohr** [comment]
Concerning your remark "if you use quotes around the searching phrase, it is treated as an exact match, meaning it is also sensitive for uppercase characters, therefore X-ray is found, while x-ray would be excluded." -> please change, it should not take into account the case. We have a lot of ebooks coming with upper case at all the letters of the titles, while other records have lower case in the titles. It will lead to not finding books if we have to search for both.

**Comment by kpsherva** [comment]
decided to add the buttpn in the search helper (shortcut)

**Comment by lydipi** [comment]
Would it be possible to do a bulk modification to avoid having upper case? that would reduce silence when doing a research.
For e-items sources:
SPRINGER -> springer
SAFARI -> safari
And all others source names that are in uppercase

For recipient:
PATRON -> patron
LIBRARY -> library
BOOKSHOP -> bookshop

**Comment by lydipi** [comment]
Would it be possible to at least clean the data and have all the e-items ressources written the same? it doesn't make sense that same sources are written differently (safari OR SAFARI).
If we have everything written in uppercase, at least we would know that we need to use only uppercase when doing a research.
