### ISSUE TITLE
Migration - access rights

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#77]
fix access rights assignment
- [ ] resolve the collections related access rights, 
- [ ] cds-admin should not be added as update and read it will be handled with roles

https://github.com/CERNDocumentServer/cds-books/pull/62/files#diff-544d0d3a848204dc16f76e141d0c792fR55

**Comment by ntarocco** [comment]
We should not have this in ILS, no access restrictions. To be checked...

**Comment by kprzerwa** [comment]
restrictions removed
