### ISSUE TITLE
CERN configuration to override ILS

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-ils#80]
Double check the full `config.py` in `invenio-app-ils` and `invenio-circulation`.
To customize:
* all `CIRCULATION_POLICIES`
    * [x] `circulation_default_loan_duration`: items have different circulation restrictions and some can loaned only for 2 weeks, some for 4 weeks. This should check the `item` restriction and return the right duration. Same for `duration_validate`
  * [ ] ILS_LOAN_WILL_EXPIRE_DAYS
* E-mail config and templates
  * [ ] ILS_MAIL_ENABLE_TEST_RECIPIENTS
  * [ ] ILS_MAIL_NOTIFY_TEST_RECIPIENTS
  * [x] ILS_MAIL_LOAN_TEMPLATES (No longer exists)
  * [x] ILS_MAIL_DOCUMENT_REQUEST_TEMPLATES (No longer exists)
  * [x] ILS_MAIL_LOAN_MSG_LOADER (No longer exists)
  * [x] ILS_MAIL_LOAN_OVERDUE_REMINDER_INTERVAL (No longer exists)
  * [x] all email templates ([document](https://cernbox.cern.ch/index.php/apps/files/?dir=/__myshares/CDS%20-%20Library%20shared%20(id:294118))), in particular fix [list_loans](https://github.com/inveniosoftware/invenio-app-ils/blob/45b844720f65af0533f1bf7725cd9154ea5a3973/invenio_app_ils/circulation/tasks.py#L58) one (ask Nico :))
* [x] Locations: block creation and deletions
* [x] Circulation transitions: remove "In transit"
* `invenioConfig.js`
  * [ ] extensionsMaxCount
  * [ ] loanWillExpireDays
  * [ ] ... any other that makes sense ... ask the library!
* [ ] delivery methods

**Comment by jrcastro2** [comment]
- Email config checked 
- [x] MAIL_NOTIFY_BCC
- [x] MAIL_NOTIFY_CC
- [x] ILS_CIRCULATION_MAIL_OVERDUE_REMINDER_INTERVAL
- [x] SECURITY_CONFIRM_EMAIL_WITHIN
- [x] SECURITY_SEND_REGISTER_EMAIL
- [x] SECURITY_SEND_PASSWORD_CHANGE_EMAIL
- [x] SECURITY_SEND_PASSWORD_RESET_EMAIL
- [x] SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL
- [x] MAIL_DEBUG
- [x] SECURITY_EMAIL_SUBJECT_CONFIRM
- [x] SECURITY_EMAIL_SUBJECT_PASSWORDLESS
- [x] SECURITY_EMAIL_SUBJECT_PASSWORD_NOTICE
- [x] SECURITY_EMAIL_SUBJECT_PASSWORD_CHANGE_NOTICE
- [x] SECURITY_EMAIL_SUBJECT_PASSWORD_RESET
- [x] SECURITY_EMAIL_PLAINTEXT
- [x] SECURITY_EMAIL_HTML
- [x] SECURITY_MSG_EMAIL_CONFIRMED
- [x] SECURITY_MSG_EMAIL_ALREADY_ASSOCIATED
- [x] SECURITY_MSG_EMAIL_NOT_PROVIDED
- [x] SECURITY_MSG_INVALID_EMAIL_ADDRESS
