### ISSUE TITLE
New Audiobooks and Videos document types

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-ils#805]
The O'Reilly (SAFARI) platform also provides audiobooks and videos.

### New Content Types
AUDIOBOOK
VIDEO

When importing, distinguish:
BOOK -> am in field LDR
AUDIOBOOK -> im in field LDR
VIDEO -> gm in field LDR

Accordingly, adapt the description on the e-items:
BOOK -> e-book
AUDIOBOOK -> audiobook
VIDEO -> video

In other catalogues, audiobooks and videos are treated as the following:

### Worldcat

*Format*:

* Book
* Print Book
* eBook
* Audiobook
* Video

### Swisscovery

*Resource Type*:

* Films
* Books
* Other (videos under this resource type)
* Audio

*Publication Format*:

* Electronic Books
* Audiobooks
* Electronic Videos
* Online Resource
* Multimedias

### TIB

*Type of media*:
* Book
* Audio-visual
* Audio file

*Type of material*:
* Electronic resources
* Print
* Audio-visual

### British Library

*Material Type*:
* Moving Image
* Books
* Audio

*Access Options*:
* Online
* Shelved

### Zenodo

*Type*:
* Publication
* Book
* Video/Audio

### Amazon
*See all formats and editions*:
* Kindle
* Audiobook
* Hardcover
* Paperback

## Proposal 
- An Audiobook can be of Document Type Book. Audiobook are added to existing Book record as additional e-item with description 'Audiobook'. If there is no record, a Book record is created with an e-item with description 'Audiobook'. ISBNs identified as '(electronic audio bk.)' (020 subfield q) should refer to Material 'Audiobook'. The other ISBNs should be treated as usual.
- Keep Video separated as they are courses or lessons -> Add a Document Type for Video. Add an e-item with description ‘Video’. Keep only ISBNs identified as '(electronic video)' (020 subfield q), should refer to Material 'Video'.
- Display Audiobook and Video in the Formats in the facets (based on the description in the e-items): e-book/ebook (to be standardized - please bulk update to 'e-book') -> Facet 'E-book'; Audiobook -> Facet 'Audiobook'; Video -> Facet 'Video', in the Filter by Format.
- For Deletions, distinguish Ebook/Audiobook with the LDR field (am (Book)/im (Audiobook)) to remove only the corresponding e-item. The rest of deletion process would as usual.

See attached screenshot:
![Screenshot 2023-01-12 at 16 27 34](https://user-images.githubusercontent.com/2089455/212109169-ca1d21e5-2833-47f9-afd5-c2bc1d5394c9.jpg)

XML imports:
[xml-example.zip](https://github.com/CERNDocumentServer/cds-ils/files/10403162/xml-example.zip)

**Comment by kpsherva** [comment]
to be investigated and evaluated: 

are the audiobooks and videos related with a book title - metadata to be checked

**Comment by lydipi** [comment]
O’Reilly - audio books and videos analysis

- Example with one audio book without document existing:
    - https://learning.oreilly.com/videos/how-to-initiate/125134AYPOD/
    - https://learning.oreilly.com/videos/dream-big-and/9781663729576/
    - https://learning.oreilly.com/library/view/-/9781663731999/

- Example with audio book and matching document:
    - https://learning.oreilly.com/videos/akka-in-action/9781617299216AU/
    - https://catalogue.library.cern/literature/r1x0s-8h066
    - Different authors in record, but on e-book page same. I didn’t see any link between the two web pages.
    - Same year and publisher.

    - https://learning.oreilly.com/videos/kubernetes-in-action/9781617293726AU/
    - https://catalogue.library.cern/literature/6n81m-w4z37
    - Same author, year and publisher.

- Example with video without document existing:
    - https://learning.oreilly.com/course/c-20-fundamentals/9780136875185/
    - https://learning.oreilly.com/course/skill-up-with/9780138297947/
    - https://learning.oreilly.com/course/lean-six-sigma/9781835882825/

**Comment by lydipi** [comment]
Ok for me too!

**Comment by lydipi** [comment]
I am adding Salomé's comment from issue [#865](https://github.com/CERNDocumentServer/cds-ils/issues/865) here:

I tested with 2 files and got the following results:

'videos' are well imported as such: example: https://sandbox-cds-ils.web.cern.ch/literature/08j5p-vsf95 Works!
'audiobook' that matched with an 'e-book': https://sandbox-cds-ils.web.cern.ch/backoffice/documents/y32s1-qzf62 it looks the audiobook item replaced the e-book (it should have been added - there should be 2 e-items (the 'e-book and the 'audiobook').
'audiobook' (without already existing record - new record): example: https://sandbox-cds-ils.web.cern.ch/backoffice/documents/e4k6y-c1235 Works!
You can ignore the following fields in the matching rules: {'758__4', '758__a', '758__i', '758__1'} in the importer.

Please let us know when point 2 in the above comment is solved, and we will also test if the importer is behaving as it should for deletions (should delete the corresponding e-item (either e-book or audiobook) if both are present).

**Comment by salomerohr** [comment]
See comment on other issue related to Audiobok/Video importations.
