### ISSUE TITLE
Ebook importation: direct link for documents

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#820]
In backoffice, e-books importer. Would it be possible to make every PID as a link? for example when I do an import, there is direct link to the concerned documents. But for deletions, there is no clickable link for document, just the PID. You can see an example here:
<img width="1263" alt="nolink_PID" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/b70bbb7b-4814-4b57-b34c-9b94517c5299">

**Comment by kpsherva** [comment]
possible solutions:
- [ ] adding the link before storing the message as an error (basically adding an `<a>` inside the error string
- [ ] parsing the error on the frontend to identify the PIDs - not ideal
