### ISSUE TITLE
Changing all "ebooks" into "e-books"

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#822]
In backoffice. For some e-books, the description URL is still "ebook" and not "e-book" as it should be.

**Comment by hacksh4w** [comment]
cud i please give this a try

**Comment by kpsherva** [comment]
> cud i please give this a try

@hacksh4w Hello! thank you for your interest in the development. Unfortunately, some of the issues, like this one, are already scheduled to be implemented by associated dev team.

**Comment by salomerohr** [comment]
I still see 'ebook' without the dash e.g. on : https://sandbox-cds-ils.web.cern.ch/backoffice/eitems/mag8c-47r43

**Comment by salomerohr** [comment]
I found this one without dash as well: https://sandbox-cds-ils.web.cern.ch/backoffice/eitems/x9esb-zfn75
