### ISSUE TITLE
See ILL on the document page

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#823]
In backoffice. It would very practical to see when there is an interlibrary loan on the document page. For example, for this [book](https://catalogue.library.cern/backoffice/documents/b3hbh-jye95), I can only know there is an ILL because there is 1 active loan, but no physical copy. But if we can have a link to the [ILL](https://catalogue.library.cern/backoffice/ill/borrowing-requests/mcfbp-9zx09) from the document page, it would be very helpful.

**Comment by salomerohr** [comment]
Looks good!

**Comment by lydipi** [comment]
Ok for me too!
