### ISSUE TITLE
Tag "Yellow report"

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#824]
Both front and backoffice. To make yellow reports more findable for users, would it be possible to add a "Yellow report" tag, like "Thesis" or "Ombud"?

**Comment by kpsherva** [comment]
more tags to be added:
WOMEN_IN_TECHNOLOGY
DIVERSITY_AND_INCLUSION

**Comment by lydipi** [comment]
Ok for me!

**Comment by kpsherva** [comment]
> Ok for me! Would it be possible to do a bulk update for the yellow reports?

I think it could be done, however could you provide us with a list of records which should be tagged as yellow report?

**Comment by lydipi** [comment]
All documents in the following series:
https://catalogue.library.cern/backoffice/series/nfht2-8h582
https://catalogue.library.cern/backoffice/series/p27q0-pz698
https://catalogue.library.cern/backoffice/series/kf7v8-sxk97
