### ISSUE TITLE
Edition not always in order in front office

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#827]
In front office. I notice that sometimes editions are not in the right order, [for example](https://catalogue.library.cern/literature/z0maq-x0x40), editions are in this order: ed. 4th; ed. 3rd; ed. 1st.
<img width="351" alt="editions_order" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/4f799560-06f4-4132-b9f7-76b2058fde3f">
Another example with more complex editions names: https://catalogue.library.cern/literature/3ngs2-mve49

decision: sort by publication year

**Comment by lydipi** [comment]
Another example with more complex editions names: https://catalogue.library.cern/literature/3ngs2-mve49

**Comment by kpsherva** [comment]
@lydipi could you add a link to the record where is it not working?

**Comment by lydipi** [comment]
It is the same document as my example : https://sandbox-cds-ils.web.cern.ch/literature/5mb93-4wj03

**Comment by salomerohr** [comment]
Looks fine to me!

**Comment by lydipi** [comment]
Ok for me too :)
