### ISSUE TITLE
Bug with phonebook link on patron page

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#829]
In back office. For every patron, there is a direct link to the CERN phonebook from their page in ILS, but now this link is not working anymore because patron's ID are not visible in the phonebook anymore. Here is an example after clicking on the link:
<img width="817" alt="phonebook" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/08a96b49-f3bd-4bbb-ad02-0dc82e0ec761">

**Comment by kpsherva** [comment]
Could you please describe the bug in more details? Otherwise it is not clear to us what the problem is
