### ISSUE TITLE
Show edition more clearly on the record in front office

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#830]
In front office. When a book has different editions, it would be helpful to see more clearly which edition it is, ideally on the top of the page like in back office. [For example](https://catalogue.library.cern/literature/h67bm-q9182):
<img width="1037" alt="beam_back" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/71523770-45a5-4a7d-bb60-0dfdeb0d9c4a">
<img width="1252" alt="beam_front" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/4b73bee6-0503-482f-acf0-8aed6e4dcd7c">

**Comment by salomerohr** [comment]
Looks good!

**Comment by lydipi** [comment]
Perfect for me!
