### ISSUE TITLE
Browse by subjects on book record

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#832]
In front office. To help user find similar literature, it would be helpful to have a link to similar subjects, like the EMBL library did ([example](https://libcatalog.embl.de/cgi-bin/koha/opac-detail.pl?biblionumber=7023&query_desc=kw%2Cwrdl%3A%20cosmology)) with "Browse shelf".

**Comment by kpsherva** [comment]
split task to two parts:  link to search by subject (show all books with the subject)
2: UI "Browse shelf"

**Comment by salomerohr** [comment]
Looks very nice! Amazing! Would it be possible, if we give you a list of correspondence, to include e-books on the same topic (based on 'subjects.value' on the document? There are various classifications, different from the one we use (we use UDC - but we received ebooks records with LOC or DEWEY).

**Comment by lydipi** [comment]
OK for me !

**Comment by salomerohr** [comment]
We are thinking about it and would like to start working on the LOC/DEWEY correspondence.  How would you like to proceed:

1. Wait for us to complete an Excel list to implement the e-book correspondence at the same time as the one you already did UDC (physical books).

or

2. Implement already the feature now (knowing it only shows physical books) - maybe change the 'More on this subject' to something like 'More paper? or physical? books on this subject'? And change the title back afterwards when we are ready to integrate the e-books?
