### ISSUE TITLE
Require before a certain date

### ISSUE THREAD

**Issue by salomerohr** [CERNDocumentServer/cds-ils#835]
**Is your feature request related to a problem? Please describe.**
People can now select very near dates for loan requests in 'I require it before a certain date', which means that if they place the request in the evening and select the same day, the loan request will be cancelled at midnight and we will not be able to fulfill it. 

**Describe the solution you'd like**
Grey today and tomorrow, so people can only place request in 2 days which let us time to process it. If we are November 7:

![image](https://github.com/CERNDocumentServer/cds-ils/assets/80258882/0a1a0311-6aab-48e3-9880-e0cd69c3fcd2)

**Comment by salomerohr** [comment]
We are on March 8 and I well see that March 8 is greyed. I see that Monday 11 can be selected. Should we go for 2 working days so Monday should be greyed as well?

**Comment by lydipi** [comment]
Ok for me!
