### ISSUE TITLE
Series: make series name case unsensitive + (series or ser) not detectable

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#838]
In back office. To avoid series duplicated when new e-books are imported because series names can sometimes be slightly different. For example, to be able to detect that the following are the same series:
- Chapman & Hall ecotoxicology series
- Chapman & Hall ecotoxicology
- Chapman & Hall Ecotoxicology Series
- Chapman & Hall Ecotoxicology
- Chapman & Hall Ecotoxicology Ser
- Chapman & Hall ecotoxicology ser

**Comment by kpsherva** [comment]
agreed to remove the suffix "Series" to have one reference titile in the system, and then match accordingly

**Comment by kpsherva** [comment]
@lydipi we have processed the series titles on sandbox, please check if this is what you've expected. To make it easier we also exported the list of the modifications into a file:

[clc_series_title_fixes.csv](https://github.com/CERNDocumentServer/cds-ils/files/14590340/clc_series_title_fixes.csv)

**Comment by lydipi** [comment]
One additional comment, is there something to test about making series name case unsensitive?

**Comment by kpsherva** [comment]
the fixes for upper/lowercase matching were already implemented in another task
