### ISSUE TITLE
Remove "CERN Central library" from display

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#843]
In back office. We noticed that it was confusing that the location was "CERN Central Library > CERN Depot 1...". Would it be possible to remove the general location, which is always "CERN Central Library"?
Here is a screenshot to illustrate it:
<img width="1276" alt="Capture d’écran 2023-12-07 à 13 17 56" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/9168953c-e27d-446d-9efa-cc304185be03">
<img width="1506" alt="Capture d’écran 2023-12-08 à 16 58 23" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/b586c412-50ca-41d0-a227-c732dd1a7b72">

**Comment by kpsherva** [comment]
possible solutions:
Rename CERN Central Library Location to CERN Library
rename CERN Central Library internal location to Central Library (remove CERN prefix)

**Comment by lydipi** [comment]
Would it be possible to display only the "Internal location" and remove the location "CERN Library" from what is visible on the page (cf. screenshots above)? 
When people at the desk first see "CERN library", they think about the central library and the books are then placed in the wrong location.
