### ISSUE TITLE
Alternative title disappears when adding metadata in another field

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#853]
In back office. I have noticed that sometimes (it is not systematic) when we create or modify a document, the alternative title field can disappear.
The process is like that: we add an alternative title field, fill it in, select language and type, and when we fill in another field further down, the alternative title field has disappeared in the meantime. It must then be recreated and filled in again.
It happened several times to me or my colleagues, for example when Flavio created this new document: https://catalogue.library.cern/backoffice/documents/4fdp2-64089. Not sure if it can help you, but it happened on 26/01/24 at 10:12 am.

**Comment by sakshamarora1** [comment]
It happens exactly when Enter is pressed on a text field in another array field's item.
It focuses only on the **first** array field's (of the form) trash and add item button.

Visual:
https://github.com/CERNDocumentServer/cds-ils/assets/50872172/23969657-7631-4c00-9f99-bfad227603dd

**Comment by lydipi** [comment]
Hello,

My colleague Flavio Gili reported that it happened again several times. He sent me an example attached to this comment.
[notice qui marche pas.odt](https://github.com/CERNDocumentServer/cds-ils/files/14695870/notice.qui.marche.pas.odt)

**Comment by sakshamarora1** [comment]
Hello @lydipi, did this happen in production or in sandbox? Because it is only deployed in sandbox and not production yet.

**Comment by lydipi** [comment]
Of course, silly me ! it was not in sandbox. Forget my comment :)
