### ISSUE TITLE
write a script to dump all physical items location and shelf

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-ils#856]
Below expected script output in .csv file. 

| Eitem PID | Document title | Location (human readable)| Shelf |
|--------|--------|--------|--------|
| abcw-defg | "ABC of magic" | Library | 403.px LOC |

- [ ] test the script on sandbox
- [ ] if all good run on prod (you can ask assistance from someone if I am not available)

**Comment by sakshamarora1** [comment]
PR: https://gitlab.cern.ch/cds-team/production_scripts/-/merge_requests/18

**Comment by kpsherva** [comment]
comments added in the PR
