### ISSUE TITLE
Link locations on opening hours page

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-ils#862]
> Looks good! What would you think of adding a link to the locations:
> 
> Library 52/1-052: https://maps.cern.ch/?n=[%273/1-003%27,%2752/1-052%27,%2752/1-204%27]
> 
> Desk 52/1-054: https://maps.cern.ch/?n=[%2752/1-054%27] 

 _Originally posted by @salomerohr in [#353](https://github.com/CERNDocumentServer/cds-ils/issues/353#issuecomment-1985547394)_

**Comment by lydipi** [comment]
Ok for me!
