### ISSUE TITLE
Importer: import audiobooks

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-ils#865]
- An Audiobook can be of Document Type Book. Audiobook are added to existing Book record as additional e-item with description 'Audiobook'. If there is no record, a Book record is created with an e-item with description 'Audiobook'. ISBNs identified as '(electronic audio bk.)' (020 subfield q) should refer to Material 'Audiobook'. The other ISBNs should be treated as usual. Important: `<leader>` field should include value `im` to identify as audiobook
- Display Audiobook  in the Formats in the facets (based on the description in the e-items): e-book/ebook (to be standardized - please bulk update to 'e-book') -> Facet 'E-book'; Audiobook -> Facet 'Audiobook';  in the Filter by Format.
- For Deletions, distinguish Ebook/Audiobook with the LDR field (am (Book)/im (Audiobook)) to remove only the corresponding e-item. The rest of deletion process would as usual.

**Comment by salomerohr** [comment]
I tested with 2 files and got the following results:
- 'videos' are well imported as such: example: https://sandbox-cds-ils.web.cern.ch/literature/08j5p-vsf95 Works!
- 'audiobook' that matched with an 'e-book': https://sandbox-cds-ils.web.cern.ch/backoffice/documents/y32s1-qzf62 it looks the audiobook item replaced the e-book (it should have been added - there should be 2 e-items (the 'e-book and the 'audiobook').
- 'audiobook' (without already existing record - new record): example: https://sandbox-cds-ils.web.cern.ch/backoffice/documents/e4k6y-c1235 Works!

You can ignore the following fields in the matching rules: {'758__4', '758__a', '758__i', '758__1'} in the importer.

**Comment by salomerohr** [comment]
Please let us know when point 2 in the above comment is solved, and we will also test if the importer is behaving as it should for deletions (should delete the corresponding e-item (either e-book or audiobook) if both are present).

**Comment by lydipi** [comment]
Perfect, it is working with the importer for audiobooks! it has added the audiobook without deleting the e-book.

**Comment by salomerohr** [comment]
Ok!
