### ISSUE TITLE
remove upper case label

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-ils#866]
> In addition to Salomé's comments, could you please change "Returned Date" with "Returned date":
> 
> <img width="1163" alt="Capture d’écran 2024-03-13 à 11 41 20" src="https://github.com/CERNDocumentServer/cds-ils/assets/148760346/960db55e-4c6b-4f5c-ae1a-7779fe272950"> 

 _Originally posted by @lydipi in [#729](https://github.com/CERNDocumentServer/cds-ils/issues/729#issuecomment-1994087806)_

**Comment by lydipi** [comment]
Ok for me!
