### ISSUE TITLE
Write upgrade recipe

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-ils#885]
For the upcoming deployment we need to make sure we are able to correctly update from current version to next one (due to data model changes). For example we need to add new fields to the mappings on sandbox and prod. Is there anything else we need to remember to deploy the latest batch of issues? (see https://github.com/inveniosoftware/invenio-app-ils/pull/1205#pullrequestreview-2011013939)
the upgrade instruction can be stored here

**Comment by kpsherva** [comment]
invenio vocabulary index json --force cds_ils/vocabularies/data/eitem_sources.json

**Comment by sakshamarora1** [comment]
1. Reindex brwReqs

```
invenio index reindex -t illbid
invenio index run
```

2. Reindex docs
```
invenio index reindex -t docid
invenio index run
```

3. Reindex purchase orders
```
invenio index reindex -t acqoid
invenio index run
```
