### ISSUE TITLE
CERN Maps does not load

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-ils#890]
**Describe the bug**
The CERN Map does not load in certain situations, showing an error. Tested from outside CERN network in Sandbox [here](https://sandbox-cds-ils.web.cern.ch/literature/89vxv-70502), with tunnelling activated.

**To Reproduce**
1. Go to a book landing page (probably from outside CERN network)
2. See the error in the iframe of the map

**Screenshots**
![Screenshot 2024-05-16 at 10 10 31](https://github.com/CERNDocumentServer/cds-ils/assets/2089455/49b88ba4-bbaf-47ad-b039-3b038a049fa1)

**Additional context**
CORS is blocking the loading of the CERN Maps.
`Referrer Policy: strict-origin-when-cross-origin`

**Comment by salomerohr** [comment]
great!
