### ISSUE TITLE
Go Live

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-ils#90]
## Admin

- [x] Define a rollback plan
- [x] Define the support channel with the library
- [x] Review issues to be implemented after production: create a board with all the majors and ask the library to prioritize
- [x] Keep monitoring Sentry exceptions

## CDS-ILS

- [x] Change the `setup` script to block it in PROD, if by mistake is run. Change the script to exist if `SENTRY_ENVIRONMENT == 'prod'`
- [x] Review env full config and enable email sending
- [x] check if ILS prod is accessbile from outside CERN

## CDS

- [x] Disable circulation module: it would be nice to keep bibcirculation running in read only mode for librarians but remove all Loan buttons or Available copies.
- [ ] Setup redirection of old URLs (My loans) to CDS-ILS
  - Change template to display a link to CDS-ILS when there is the tag ILSSYNC
    - `980__c:MIGRATED` + `970__d: url`
- [x] Remove the circulation bibsched tasks
- [ ] Ensure the sync task is running in bibsched (separate ticket created)

## External sites

- [x] Ensure that links in the libray.cern website are updated
- [x] Ensure that EDH Termination Sheet ready to switch
- [x] Update links from [LMS](https://lms.cern.ch/ekp/servlet/ekp?CID=EKP000043380&TX=FORMAT1&BACKTOCATALOG=Y&DECORATEPAGE=N)
- [x] Ensure that EBookCentral/EBL/Proquest/EZProxy are correctly configured

## RoPo
https://github.com/CERNDocumentServer/cds-ils/issues/490
- [ ] RoPo for CDS-ILS has been created.
- [ ] Modify the RoPo for CDS to remove the ILS part.

## After launch/migration

(separate tickets created)

- [x] enable email sending in production
- [ ] remove environment specific users from storage access egroup
- [ ] Disable EDH endpoint in CDS
- [ ] Remove the migrator PODs and Build/Deployment configs
- [x] Create UpTimeRobot page and Status page
- [x] Update the headers in the Mattermost channels to add CDS-ILS
- [ ] SNow: do we need a dedicated functional element?
- [ ] Do we migrate view/download stats?

Notes: https://codimd.web.cern.ch/ihuis8BQQryqb3PvZtw_0Q
Collections modifications on legacy
[modifs_on_cds.txt](https://github.com/CERNDocumentServer/cds-ils/files/6304806/modifs_on_cds.txt)

**Comment by kprzerwa** [comment]
created separate tickets for some subpoints, closing
